apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: default  # Confirmado que el namespace es "default"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-server
spec:
  type: NodePort
  ports:
    - port: 80               # Puerto estándar para acceder externamente
      targetPort: 9090       # Puerto en el que Prometheus escucha internamente
      nodePort: 32003        # Elige un NodePort que esté disponible
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus #corregido , antes era prometheus-server y no se lograba conectar con Grafana
